// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarefas.Data;

#nullable disable

namespace Tarefas.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230303125202_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tarefas.Data.Models.StatusTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusTarefas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9"),
                            Descricao = "A Fazer"
                        },
                        new
                        {
                            Id = new Guid("2ac70bb3-51b9-41ea-af72-cc9e173656f0"),
                            Descricao = "Em Desenvolvimento"
                        },
                        new
                        {
                            Id = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36"),
                            Descricao = "Concluído"
                        });
                });

            modelBuilder.Entity("Tarefas.Data.Models.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("DATE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Tarefas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c69dfb9-7cbc-4d78-bd7d-6fe2650a9597"),
                            DataPrevisao = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Avaliar arquitetura do projeto",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("744e4db9-8180-479c-86b2-ea5848871cd6"),
                            DataPrevisao = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Definição do design front-end",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("040258a2-44cc-4774-ba9a-d5f86eebfc18"),
                            DataPrevisao = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Desenvolver POC do projeto",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("1f3aa0b2-f206-49a5-8dfb-3ec8f0380f23"),
                            DataPrevisao = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Desenvolver Web API",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("660ef6e7-35a4-4fbb-9937-af8c556251b3"),
                            DataPrevisao = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Desenvolver Worker Service",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("f0762883-5b76-4ec9-b710-fad70bbfe133"),
                            DataPrevisao = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Criar conexão Web API + Worker",
                            StatusId = new Guid("4698842e-e9b6-4abf-af78-58c336bc4e36")
                        },
                        new
                        {
                            Id = new Guid("b28c8038-3589-4479-95d4-cdd5c648b903"),
                            DataPrevisao = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Desenvolver front-end com Angular",
                            StatusId = new Guid("2ac70bb3-51b9-41ea-af72-cc9e173656f0")
                        },
                        new
                        {
                            Id = new Guid("34c1fd4c-08c6-41b0-99b7-b1439ad13419"),
                            DataPrevisao = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Testar comunicação ponta a ponta",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        },
                        new
                        {
                            Id = new Guid("d8a25c88-20d8-449e-aa2b-a03e9dd9d2f1"),
                            DataPrevisao = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Versionar projeto GitHub",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        },
                        new
                        {
                            Id = new Guid("b8ce2d75-73d1-404c-8cc4-8e621f742130"),
                            DataPrevisao = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Documentar como utilizar o projeto README",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        },
                        new
                        {
                            Id = new Guid("6a7ddd07-d46e-490e-bee4-40b310426772"),
                            DataPrevisao = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "(Extra) Containerizar toda a aplicação com docker compose",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        },
                        new
                        {
                            Id = new Guid("63ae46d3-3861-4414-a08a-d92505d251d7"),
                            DataPrevisao = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "(Extra) Documentar utilização via container o projeto README",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        },
                        new
                        {
                            Id = new Guid("5483b675-437a-4271-89e0-743e4ddd7384"),
                            DataPrevisao = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Adicionar logs para suporte da aplicação",
                            StatusId = new Guid("212f1c70-5de2-41df-8c85-e36c30e89fe9")
                        });
                });

            modelBuilder.Entity("Tarefas.Data.Models.Tarefa", b =>
                {
                    b.HasOne("Tarefas.Data.Models.StatusTarefa", "Status")
                        .WithMany("Tarefas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Tarefas.Data.Models.StatusTarefa", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
